"""Small, provenance-backed city route ideas used as planning hints.

These are curated route concepts, not live popularity measurements or stored
route geometry. Google Routes remains authoritative for the returned line.
"""

from __future__ import annotations

from dataclasses import dataclass
import re
import unicodedata


@dataclass(frozen=True)
class RouteTemplate:
    template_id: str
    name: str
    description: str
    start_terms: tuple[str, ...]
    end_terms: tuple[str, ...]
    tags: tuple[str, ...]
    suggested_stops: tuple[str, ...]
    waypoint_hints: tuple[str, ...]
    source_url: str
    city: str = "london"


LONDON_ROUTE_TEMPLATES: tuple[RouteTemplate, ...] = (
    RouteTemplate("fulham-richmond-park", "Fulham to Richmond Park", "A green west-London ride linking the riverside and Richmond Park.", ("fulham", "putney", "hammersmith"), ("richmond park", "richmond"), ("scenic", "quiet", "park"), ("cafe", "public_bathroom", "restaurant"), ("Thames Path", "Richmond Park"), "https://www.visitrichmond.co.uk/see-and-do/richmond-park"),
    RouteTemplate("richmond-park-loop", "Richmond Park Loop", "A flexible loop around Richmond Park with parkland views and wildlife stops.", ("richmond park", "richmond"), ("richmond park", "richmond"), ("scenic", "quiet", "park", "interesting"), ("cafe", "public_bathroom", "restaurant"), ("Richmond Park",), "https://www.royalparks.org.uk/visit/parks/richmond-park"),
    RouteTemplate("thames-path", "Thames Path", "A riverside route concept for relaxed, scenic west and central London journeys.", ("fulham", "putney", "hammersmith", "chelsea"), ("richmond", "kingston", "westminster"), ("scenic", "quiet", "interesting"), ("cafe", "restaurant"), ("Thames Path",), "https://www.nationaltrail.co.uk/en_GB/trails/thames-path/"),
    RouteTemplate("hyde-park-regents-canal", "Hyde Park to Regent's Canal", "A park-and-canal concept connecting central London green spaces.", ("hyde park", "kensington", "paddington"), ("regent's canal", "camden", "little venice"), ("scenic", "park", "interesting"), ("cafe", "restaurant", "public_bathroom"), ("Hyde Park", "Regent's Canal"), "https://www.visitlondon.com/things-to-do/visiting-london-with-kids/parks-and-open-spaces"),
    RouteTemplate("greenwich-park-thames", "Greenwich Park and Thames", "A heritage and riverside route concept through Greenwich and the Thames waterfront.", ("greenwich", "canary wharf", "london bridge"), ("greenwich", "cutty sark", "thamesmead"), ("scenic", "park", "interesting"), ("cafe", "restaurant", "public_bathroom"), ("Greenwich Park", "Thames Path"), "https://www.royalparks.org.uk/visit/parks/greenwich-park"),
    RouteTemplate("wandle-trail", "Wandle Trail", "A south-London river route concept linking parks, mills, and quieter paths.", ("wimbledon", "earlsfield", "tooting", "croydon"), ("wandsworth", "morden", "croydon"), ("quiet", "scenic", "interesting"), ("cafe", "public_bathroom", "restaurant"), ("Wandle Trail", "Wandle Park"), "https://wandle.group/wandle-trail/"),
    RouteTemplate("lee-valley", "Lee Valley Waterways", "A waterside route concept through northeast London waterways and green spaces.", ("hackney", "stratford", "tottenham", "walthamstow"), ("lee valley", "waltham abbey", "enfield"), ("quiet", "scenic", "park"), ("cafe", "public_bathroom", "restaurant"), ("Lee Valley", "River Lea"), "https://www.visitleevalley.org.uk/"),
    RouteTemplate("epping-forest", "Epping Forest", "A woodland-edge route concept for a greener northeast London ride.", ("leytonstone", "wanstead", "woodford", "stratford"), ("epping forest", "loughton", "high beach"), ("scenic", "quiet", "park", "interesting"), ("cafe", "public_bathroom", "restaurant"), ("Epping Forest", "High Beach"), "https://www.cityoflondon.gov.uk/services/parks-open-spaces/epping-forest"),
    RouteTemplate("regents-canal-loop", "Regent's Canal Loop", "A canal-side loop concept through Little Venice, Camden, and Victoria Park.", ("little venice", "paddington", "camden", "islington"), ("victoria park", "hackney wick", "little venice"), ("scenic", "quiet", "interesting"), ("cafe", "restaurant", "public_bathroom"), ("Regent's Canal", "Victoria Park"), "https://canalrivertrust.org.uk/canals-and-rivers/places-to-visit/regents-canal"),
    RouteTemplate("parks-greenway", "Central London Parks Greenway", "A connected-park route concept between Hyde Park, Kensington Gardens, and Regent's Park.", ("hyde park", "kensington", "westminster"), ("regent's park", "primrose hill", "camden"), ("scenic", "park", "interesting"), ("cafe", "public_bathroom", "restaurant"), ("Hyde Park", "Regent's Park", "Primrose Hill"), "https://www.royalparks.org.uk/visit/parks"),
    RouteTemplate("hampstead-heath", "Hampstead Heath", "A north-London parkland route concept with views across the city.", ("camden", "kentish town", "finchley"), ("hampstead heath", "hampstead", "highgate"), ("scenic", "quiet", "park"), ("cafe", "restaurant", "public_bathroom"), ("Hampstead Heath", "Parliament Hill"), "https://www.cityoflondon.gov.uk/services/parks-open-spaces/hampstead-heath"),
    RouteTemplate("royal-docks-greenway", "Royal Docks Greenway", "An east-London waterside route concept around the Royal Docks.", ("canary wharf", "stratford", "custom house"), ("royal docks", "beckton", "woolwich"), ("scenic", "quiet", "interesting"), ("cafe", "restaurant"), ("Royal Victoria Dock", "Thames Barrier"), "https://www.royaldocks.london/"),
    RouteTemplate("hampstead-to-regents", "Hampstead to Regent's Park", "A green north-London connection between two major parks.", ("hampstead", "kentish town", "camden"), ("regent's park", "primrose hill", "marylebone"), ("scenic", "park", "quiet"), ("cafe", "public_bathroom"), ("Hampstead Heath", "Primrose Hill"), "https://www.royalparks.org.uk/visit/parks/regents-park"),
    RouteTemplate("south-bank-greenway", "South Bank and Battersea", "A central riverside concept linking South Bank to Battersea Park.", ("south bank", "waterloo", "london bridge"), ("battersea", "battersea park", "vauxhall"), ("scenic", "interesting", "quiet"), ("cafe", "restaurant", "public_bathroom"), ("South Bank", "Battersea Park"), "https://www.visitlondon.com/things-to-do/whats-on/south-bank"),
    RouteTemplate("wimbledon-richmond", "Wimbledon to Richmond Park", "A southwest parks connection between Wimbledon and Richmond.", ("wimbledon", "putney", "earlsfield"), ("richmond park", "richmond", "kingston"), ("scenic", "quiet", "park"), ("cafe", "restaurant", "public_bathroom"), ("Wimbledon Common", "Richmond Park"), "https://www.royalparks.org.uk/visit/parks/richmond-park"),
)

CITY_ROUTE_TEMPLATES: tuple[RouteTemplate, ...] = LONDON_ROUTE_TEMPLATES + (
    RouteTemplate("hudson-greenway", "Hudson River Greenway", "A waterfront route concept along Manhattan's west side.", ("midtown", "chelsea", "battery park"), ("upper west side", "inwood", "george washington bridge"), ("scenic", "quiet", "interesting"), ("cafe", "restaurant", "public_bathroom"), ("Hudson River Greenway",), "https://www.nyc.gov/html/dot/html/bicyclists/bikemap.shtml", "new_york"),
    RouteTemplate("central-park-loop-nyc", "Central Park Loop", "A landmark park loop concept for a central Manhattan ride.", ("central park", "midtown", "upper west side"), ("central park", "harlem", "midtown"), ("scenic", "park", "interesting"), ("cafe", "public_bathroom", "restaurant"), ("Central Park",), "https://www.centralparknyc.org/activities/biking", "new_york"),
    RouteTemplate("brooklyn-waterfront", "Brooklyn Waterfront", "A waterfront and bridge-view route concept through Brooklyn.", ("brooklyn", "dumbo", "williamsburg"), ("brooklyn bridge park", "red hook", "prospect park"), ("scenic", "interesting", "quiet"), ("cafe", "restaurant"), ("Brooklyn Bridge Park",), "https://www.brooklynbridgepark.org/park/visit/", "new_york"),
    RouteTemplate("prospect-park-loop", "Prospect Park Loop", "A relaxed park loop concept in Brooklyn.", ("prospect park", "park slope", "brooklyn"), ("prospect park", "flatbush", "brooklyn"), ("scenic", "park", "quiet"), ("cafe", "restaurant", "public_bathroom"), ("Prospect Park",), "https://www.prospectpark.org/visit/activities/cycling/", "new_york"),
    RouteTemplate("queensboro-waterfront", "Queensboro Waterfront", "A waterfront concept from Queens to Long Island City.", ("astoria", "queens", "jackson heights"), ("long island city", "gantry plaza", "roosevelt island"), ("scenic", "interesting", "quiet"), ("cafe", "restaurant"), ("Gantry Plaza State Park",), "https://parks.ny.gov/parks/gantryplaza/", "new_york"),
    RouteTemplate("riverside-park", "Riverside Park", "A Hudson-side park route concept on Manhattan's west side.", ("upper west side", "morningside heights", "harlem"), ("riverside park", "george washington bridge", "inwood"), ("scenic", "quiet", "park"), ("cafe", "public_bathroom"), ("Riverside Park",), "https://www.nycgovparks.org/parks/riverside-park", "new_york"),
    RouteTemplate("east-river-greenway", "East River Greenway", "A Manhattan waterfront route concept along the East River.", ("battery park", "lower east side", "midtown"), ("east river park", "harlem", "upper east side"), ("scenic", "quiet", "interesting"), ("cafe", "restaurant"), ("East River Park",), "https://www.nyc.gov/html/dot/html/bicyclists/bikemap.shtml", "new_york"),
    RouteTemplate("brooklyn-greenway", "Brooklyn Greenway", "A neighborhood greenway concept across Brooklyn waterfront districts.", ("dumbo", "brooklyn heights", "red hook"), ("sunset park", "bay ridge", "brooklyn bridge park"), ("scenic", "quiet", "interesting"), ("cafe", "restaurant"), ("Brooklyn Greenway",), "https://www.bbg.org/article/brooklyn_greenway", "new_york"),
    RouteTemplate("governors-island", "Governors Island Loop", "A car-free island loop concept with harbor views.", ("battery park", "brooklyn", "lower manhattan"), ("governors island", "ferry terminal", "red hook"), ("scenic", "quiet", "park", "interesting"), ("cafe", "restaurant", "public_bathroom"), ("Governors Island",), "https://www.govisland.com/visit", "new_york"),
    RouteTemplate("van-cortlandt-park", "Van Cortlandt Park", "A northern Bronx park route concept.", ("bronx", "kingsbridge", "washington heights"), ("van cortlandt park", "riverdale", "yonkers"), ("scenic", "quiet", "park"), ("cafe", "public_bathroom"), ("Van Cortlandt Park",), "https://www.nycgovparks.org/parks/van-cortlandt-park", "new_york"),
    RouteTemplate("high-line-hudson", "High Line to Hudson Yards", "A central west-side park and waterfront concept.", ("chelsea", "meatpacking", "hudson yards"), ("hudson yards", "little island", "battery park"), ("interesting", "scenic", "park"), ("cafe", "restaurant"), ("The High Line", "Little Island"), "https://www.thehighline.org/visit/", "new_york"),
    RouteTemplate("flushing-meadows", "Flushing Meadows Loop", "A Queens park and cultural-sites route concept.", ("flushing", "corona", "queens"), ("flushing meadows", "queens museum", "citi field"), ("park", "interesting", "scenic"), ("cafe", "restaurant", "public_bathroom"), ("Flushing Meadows Corona Park",), "https://www.nycgovparks.org/parks/flushing-meadows-corona-park", "new_york"),
    RouteTemplate("rockaway-beach", "Rockaway Beach Greenway", "A coastal route concept along the Rockaways.", ("jamaica bay", "queens", "brooklyn"), ("rockaway beach", "jacob riis park", "fort tilden"), ("scenic", "quiet", "park"), ("cafe", "restaurant", "public_bathroom"), ("Rockaway Beach", "Jacob Riis Park"), "https://www.nycgovparks.org/parks/jacob-riis-park", "new_york"),
    RouteTemplate("williamsburg-waterfront", "Williamsburg Waterfront", "A North Brooklyn waterfront and bridge-view route concept.", ("williamsburg", "greenpoint", "brooklyn"), ("domino park", "brooklyn navy yard", "dumbo"), ("scenic", "interesting", "quiet"), ("cafe", "restaurant"), ("Domino Park", "East River State Park"), "https://www.nycgovparks.org/parks/domino-park", "new_york"),
    RouteTemplate("staten-island-greenbelt", "Staten Island Greenbelt", "A woodland and park route concept on Staten Island.", ("staten island", "st george", "ferry"), ("greenbelt", "clove lakes", "great kills"), ("scenic", "quiet", "park"), ("cafe", "public_bathroom"), ("Staten Island Greenbelt",), "https://www.nycgovparks.org/parks/staten-island-greenbelt", "new_york"),
    RouteTemplate("chicago-lakefront", "Chicago Lakefront Trail", "A lakefront route concept connecting parks and beaches along Lake Michigan.", ("the loop", "lincoln park", "south loop"), ("hyde park", "jackson park", "montrose"), ("scenic", "quiet", "park"), ("cafe", "public_bathroom", "restaurant"), ("Lakefront Trail", "Lincoln Park"), "https://www.chicagoparkdistrict.com/parks-facilities/lakefront-trail", "chicago"),
    RouteTemplate("606-bloomingdale", "606 and Bloomingdale Trail", "An elevated-park route concept through Chicago's northwest neighborhoods.", ("wicker park", "bucktown", "logan square"), ("606", "humboldt park", "west town"), ("scenic", "park", "interesting"), ("cafe", "restaurant"), ("The 606", "Bloomingdale Trail"), "https://www.the606.org/", "chicago"),
    RouteTemplate("burnham-greenway", "Burnham Park Greenway", "A south-side lakefront and park route concept.", ("south loop", "bronzeville", "museum campus"), ("hyde park", "burnham park", "jackson park"), ("scenic", "park", "quiet"), ("cafe", "public_bathroom", "restaurant"), ("Burnham Park", "Museum Campus"), "https://www.chicagoparkdistrict.com/parks-facilities/burnham-park", "chicago"),
    RouteTemplate("north-branch-trail", "North Branch Trail", "A forest-preserve route concept north of Chicago.", ("lincoln square", "north park", "albany park"), ("north branch trail", "skokie", "botanic garden"), ("scenic", "quiet", "park"), ("cafe", "public_bathroom"), ("North Branch Trail",), "https://fpdcc.com/places/locations/north-branch-trail-system/", "chicago"),
    RouteTemplate("606-lakefront", "606 to Lakefront", "A neighborhood-to-lake route concept from the Bloomingdale Trail.", ("logan square", "wicker park", "bucktown"), ("lincoln park", "lakefront", "belmont harbor"), ("scenic", "interesting", "park"), ("cafe", "restaurant"), ("The 606", "Lincoln Park"), "https://www.the606.org/", "chicago"),
    RouteTemplate("montrose-bird", "Montrose Harbor and Bird Sanctuary", "A lakefront park and nature route concept.", ("uptown", "ravenswood", "lakeview"), ("montrose harbor", "montrose beach", "lincoln park"), ("scenic", "quiet", "park", "interesting"), ("cafe", "restaurant", "public_bathroom"), ("Montrose Point",), "https://www.chicagoparkdistrict.com/parks-facilities/montrose-point-bird-sanctuary", "chicago"),
    RouteTemplate("chicago-riverwalk", "Chicago Riverwalk", "A downtown river and architecture route concept.", ("the loop", "river north", "west loop"), ("chicago riverwalk", "merchandise mart", "chinatown"), ("interesting", "scenic"), ("cafe", "restaurant", "public_bathroom"), ("Chicago Riverwalk",), "https://www.chicagoriverwalk.us/", "chicago"),
    RouteTemplate("douglas-park", "Douglas Park Greenway", "A west-side parks route concept through Douglas Park.", ("pilsen", "little village", "west loop"), ("douglas park", "garfield park", "humboldt park"), ("scenic", "quiet", "park"), ("cafe", "restaurant"), ("Douglas Park",), "https://www.chicagoparkdistrict.com/parks-facilities/douglas-park", "chicago"),
    RouteTemplate("garfield-park", "Garfield Park Conservatory", "A west-side park and conservatory route concept.", ("west loop", "ukrainian village", "humboldt park"), ("garfield park", "conservatory", "douglas park"), ("park", "interesting", "scenic"), ("cafe", "restaurant", "public_bathroom"), ("Garfield Park Conservatory",), "https://garfieldconservatory.org/", "chicago"),
    RouteTemplate("humboldt-park", "Humboldt Park Boulevard", "A park boulevard route concept through northwest neighborhoods.", ("logan square", "avondale", "west town"), ("humboldt park", "606", "ukrainian village"), ("scenic", "park", "quiet"), ("cafe", "restaurant"), ("Humboldt Park",), "https://www.chicagoparkdistrict.com/parks-facilities/humboldt-park", "chicago"),
    RouteTemplate("south-shore", "South Shore Cultural Trail", "A lakefront and museum route concept on Chicago's south side.", ("hyde park", "kenwood", "south shore"), ("south shore cultural center", "calumet park", "jackson park"), ("scenic", "interesting", "park"), ("cafe", "restaurant", "public_bathroom"), ("South Shore Cultural Center",), "https://www.chicagoparkdistrict.com/parks-facilities/south-shore-cultural-center", "chicago"),
    RouteTemplate("calumet-sag", "Calumet-Sag Channel", "A south-side waterside route concept through forest preserves.", ("beverly", "chicago ridge", "midway"), ("calumet-sag trail", "palos", "blue island"), ("scenic", "quiet"), ("cafe", "public_bathroom"), ("Calumet-Sag Trail",), "https://fpdcc.com/places/locations/calumet-sag-trail/", "chicago"),
    RouteTemplate("chicago-lakefront-loop", "Full Lakefront Loop", "A long-form lakefront route concept linking Chicago's major parks.", ("lincoln park", "the loop", "south loop"), ("hyde park", "jackson park", "montrose"), ("scenic", "park", "quiet"), ("cafe", "restaurant", "public_bathroom"), ("Lakefront Trail",), "https://www.chicagoparkdistrict.com/parks-facilities/lakefront-trail", "chicago"),
    RouteTemplate("union-park-west-loop", "Union Park and West Loop", "A short park and architecture route concept west of downtown.", ("west loop", "united center", "fulton market"), ("union park", "ukrainian village", "humboldt park"), ("interesting", "scenic", "park"), ("cafe", "restaurant"), ("Union Park",), "https://www.chicagoparkdistrict.com/parks-facilities/union-park", "chicago"),
    RouteTemplate("promontory-point", "Promontory Point", "A lakefront landmark route concept through Hyde Park.", ("hyde park", "kenwood", "museum campus"), ("promontory point", "31st street beach", "jackson park"), ("scenic", "park", "interesting"), ("cafe", "restaurant", "public_bathroom"), ("Promontory Point",), "https://www.chicagoparkdistrict.com/parks-facilities/promontory-point", "chicago"),
    RouteTemplate("capital-crescent", "Capital Crescent Trail", "A shaded rail-trail route concept between Georgetown and Bethesda.", ("georgetown", "foggy bottom", "dupont circle"), ("bethesda", "silver spring", "friendship heights"), ("scenic", "quiet", "park"), ("cafe", "public_bathroom", "restaurant"), ("Capital Crescent Trail",), "https://capitalcrescenttrail.org/", "washington_dc"),
    RouteTemplate("national-mall-tidal-basin", "National Mall and Tidal Basin", "A landmark loop concept around Washington's monuments and waterfront.", ("national mall", "downtown", "capitol hill"), ("tidal basin", "lincoln memorial", "national mall"), ("scenic", "park", "interesting"), ("cafe", "public_bathroom", "restaurant"), ("Tidal Basin", "National Mall"), "https://www.nps.gov/nama/planyourvisit/biking.htm", "washington_dc"),
    RouteTemplate("mount-vernon-trail", "Mount Vernon Trail", "A riverside route concept from the National Mall toward Mount Vernon.", ("alexandria", "crystal city", "national mall"), ("mount vernon", "old town alexandria", "reagan national"), ("scenic", "quiet", "interesting"), ("cafe", "restaurant", "public_bathroom"), ("Mount Vernon Trail", "Old Town Alexandria"), "https://www.nps.gov/gwmp/planyourvisit/mtvernontrail.htm", "washington_dc"),
    RouteTemplate("anacostia-riverwalk", "Anacostia Riverwalk", "A riverside and park route concept east of the Anacostia.", ("navy yard", "capitol hill", "anacostia"), ("anacostia riverwalk", "kenilworth", "watkins regional park"), ("scenic", "quiet", "park"), ("cafe", "restaurant", "public_bathroom"), ("Anacostia Riverwalk Trail",), "https://anacostiarivertrail.org/", "washington_dc"),
    RouteTemplate("rock-creek-park", "Rock Creek Park", "A wooded north-south route concept through Washington's largest urban park.", ("dupont circle", "woodley park", "georgetown"), ("rock creek park", "chevy chase", "takoma"), ("scenic", "quiet", "park"), ("cafe", "public_bathroom"), ("Rock Creek Park",), "https://www.nps.gov/rocr/planyourvisit/biking.htm", "washington_dc"),
    RouteTemplate("custis-trail", "Custis Trail", "A ridge route concept connecting Arlington and the Potomac waterfront.", ("rosslyn", "georgetown", "clarendon"), ("ballston", "falls church", "custis trail"), ("scenic", "quiet"), ("cafe", "restaurant"), ("Custis Trail",), "https://www.novaparks.com/parks/washington-and-old-dominion-railroad-regional-park", "washington_dc"),
    RouteTemplate("wod-trail", "W&OD Trail", "A long-form rail-trail concept west from Arlington.", ("arlington", "falls church", "clarendon"), ("vienna", "reston", "leesburg"), ("quiet", "scenic", "park"), ("cafe", "restaurant", "public_bathroom"), ("W&OD Trail",), "https://www.novaparks.com/parks/washington-and-old-dominion-railroad-regional-park", "washington_dc"),
    RouteTemplate("four-mile-run", "Four Mile Run Trail", "A creekside route concept through Arlington and Alexandria.", ("arlington", "crystal city", "shirlington"), ("four mile run", "alexandria", "mount vernon trail"), ("quiet", "scenic", "park"), ("cafe", "restaurant"), ("Four Mile Run",), "https://www.novaparks.com/parks/four-mile-run", "washington_dc"),
    RouteTemplate("c-and-o-canal", "C&O Canal Towpath", "A historic canal-side route concept from Georgetown toward Great Falls.", ("georgetown", "foggy bottom", "dupont circle"), ("great falls", "c&o canal", "bethesda"), ("scenic", "quiet", "interesting"), ("cafe", "restaurant", "public_bathroom"), ("C&O Canal Towpath", "Great Falls"), "https://www.nps.gov/choh/planyourvisit/bicycling.htm", "washington_dc"),
    RouteTemplate("national-arboretum", "National Arboretum", "A botanical and quiet-road route concept in northeast DC.", ("capitol hill", "noma", "brookland"), ("national arboretum", "kenilworth", "rhode island avenue"), ("scenic", "quiet", "park", "interesting"), ("cafe", "public_bathroom"), ("National Arboretum",), "https://www.usna.usda.gov/visit", "washington_dc"),
    RouteTemplate("theodore-roosevelt-island", "Theodore Roosevelt Island", "A Potomac island and monument route concept.", ("rosslyn", "georgetown", "foggy bottom"), ("theodore roosevelt island", "potomac", "rosslyn"), ("scenic", "quiet", "park", "interesting"), ("cafe", "public_bathroom"), ("Theodore Roosevelt Island",), "https://www.nps.gov/this/index.htm", "washington_dc"),
    RouteTemplate("east-potomac-park", "East Potomac Park", "A waterfront loop concept around Hains Point and the Tidal Basin.", ("national mall", "southwest", "wharf"), ("hains point", "east potomac park", "tidal basin"), ("scenic", "quiet", "park"), ("cafe", "restaurant", "public_bathroom"), ("Hains Point", "Tidal Basin"), "https://www.nps.gov/nama/planyourvisit/east-potomac-park.htm", "washington_dc"),
    RouteTemplate("bethesda-capital-crescent", "Bethesda Capital Crescent", "A neighborhood-to-trail route concept from Bethesda toward Silver Spring.", ("bethesda", "friendship heights", "chevy chase"), ("silver spring", "takoma", "capital crescent trail"), ("quiet", "scenic", "park"), ("cafe", "restaurant"), ("Capital Crescent Trail",), "https://capitalcrescenttrail.org/", "washington_dc"),
    RouteTemplate("alexandria-old-town", "Alexandria Old Town Waterfront", "A historic waterfront route concept through Old Town Alexandria.", ("old town alexandria", "alexandria", "crystal city"), ("old town waterfront", "jones point", "mount vernon trail"), ("scenic", "interesting", "quiet"), ("cafe", "restaurant", "public_bathroom"), ("Old Town Alexandria", "Jones Point"), "https://www.visitalexandriava.com/old-town/", "washington_dc"),
    RouteTemplate("fairfax-cross-county", "Fairfax Cross County Trail", "A green suburban trail concept through Fairfax County.", ("falls church", "fairfax", "arlington"), ("cross county trail", "vienna", "wakefield"), ("quiet", "scenic", "park"), ("cafe", "public_bathroom"), ("Cross County Trail",), "https://www.fairfaxcounty.gov/parks/trails/cross-county", "washington_dc"),
    RouteTemplate("copenhagen-harbour", "Copenhagen Harbour and Amager", "A waterfront and greenway concept around Copenhagen harbour and Amager.", ("indrehavn", "nyhavn", "city centre", "copenhagen"), ("amager strand", "christianshavn", "dragør"), ("scenic", "quiet", "park"), ("cafe", "restaurant", "public_bathroom"), ("Copenhagen Harbour", "Amager Strandpark"), "https://international.kk.dk/live/transport-and-parking/cycling", "copenhagen"),
    RouteTemplate("copenhagen-dyrehaven", "Copenhagen to Dyrehaven", "A northbound green route concept from the city to Dyrehaven woodland.", ("nørrebro", "østerbro", "copenhagen"), ("dyrehaven", "klampenborg", "charlottenlund"), ("scenic", "quiet", "park", "interesting"), ("cafe", "restaurant", "public_bathroom"), ("Dyrehaven", "Charlottenlund"), "https://www.visitcopenhagen.com/copenhagen/planning/cycling-copenhagen", "copenhagen"),
    RouteTemplate("copenhagen-lakes", "Copenhagen Lakes Loop", "A central lakes and green-boulevard route concept.", ("vesterbro", "nørrebro", "city centre"), ("the lakes", "søerne", "østerbro"), ("scenic", "quiet", "park"), ("cafe", "restaurant"), ("Copenhagen Lakes",), "https://international.kk.dk/live/transport-and-parking/cycling", "copenhagen"),
    RouteTemplate("copenhagen-christiania", "Christianshavn and Christiania", "A canal and cultural-sites route concept.", ("city centre", "indrehavn", "nyhavn"), ("christianshavn", "christiania", "amager"), ("interesting", "scenic", "quiet"), ("cafe", "restaurant"), ("Christianshavn", "Christiania"), "https://www.visitcopenhagen.com/copenhagen/planning/cycling-copenhagen", "copenhagen"),
    RouteTemplate("copenhagen-bispebjerg", "Bispebjerg Greenway", "A quiet neighborhood and park route concept northwest of the centre.", ("nørrebro", "frederiksberg", "copenhagen"), ("bispebjerg", "utterslev mose", "bellahøj"), ("quiet", "park", "scenic"), ("cafe", "restaurant"), ("Utterslev Mose",), "https://international.kk.dk/live/transport-and-parking/cycling", "copenhagen"),
    RouteTemplate("copenhagen-amager-loop", "Amager Nature Loop", "A nature and coast loop concept south of the harbour.", ("amager", "christianshavn", "copenhagen"), ("amager fælled", "amager strand", "kalvebod fælle"), ("scenic", "quiet", "park"), ("cafe", "public_bathroom"), ("Amager Fælled", "Amager Strandpark"), "https://www.visitcopenhagen.com/copenhagen/planning/cycling-copenhagen", "copenhagen"),
    RouteTemplate("copenhagen-carlsberg", "Carlsberg to Frederiksberg", "A parks and heritage route concept west of the centre.", ("vesterbro", "carlsberg", "city centre"), ("frederiksberg", "frederiksberg have", "zoo"), ("park", "interesting", "scenic"), ("cafe", "restaurant"), ("Frederiksberg Gardens",), "https://www.visitcopenhagen.com/copenhagen/planning/cycling-copenhagen", "copenhagen"),
    RouteTemplate("copenhagen-nordhavn", "Nordhavn Waterfront", "A modern harbour and waterfront route concept.", ("østerbro", "nordhavn", "copenhagen"), ("nordhavn", "svanemølle", "kalkbrænderihavn"), ("scenic", "interesting", "quiet"), ("cafe", "restaurant"), ("Nordhavn", "Svanemølle Beach"), "https://international.kk.dk/live/transport-and-parking/cycling", "copenhagen"),
    RouteTemplate("copenhagen-kongens-enge", "Kongens Enghave", "A harbour, park, and allotment route concept southwest of the centre.", ("vesterbro", "sydhavnen", "carlsberg"), ("kongens enghave", "valbyparken", "sluseholmen"), ("quiet", "scenic", "park"), ("cafe", "restaurant"), ("Valbyparken",), "https://international.kk.dk/live/transport-and-parking/cycling", "copenhagen"),
    RouteTemplate("copenhagen-bakery-bridge", "Langelinie and Kastellet", "A harbour landmark route concept around Kastellet and Langelinie.", ("nyhavn", "city centre", "østerbro"), ("kastellet", "langelinie", "little mermaid"), ("scenic", "interesting", "park"), ("cafe", "restaurant", "public_bathroom"), ("Kastellet", "The Little Mermaid"), "https://www.visitcopenhagen.com/copenhagen/planning/cycling-copenhagen", "copenhagen"),
    RouteTemplate("copenhagen-frederiksberg-loop", "Frederiksberg Park Loop", "A leafy park loop concept in Frederiksberg.", ("frederiksberg", "vesterbro", "carlsberg"), ("frederiksberg gardens", "søndermarken", "zoo"), ("park", "scenic", "quiet"), ("cafe", "restaurant", "public_bathroom"), ("Frederiksberg Gardens", "Søndermarken"), "https://international.kk.dk/live/transport-and-parking/cycling", "copenhagen"),
    RouteTemplate("copenhagen-klampenborg-coast", "Klampenborg Coast", "A coastal northbound route concept beyond the city.", ("østerbro", "charlottenlund", "copenhagen"), ("klampenborg", "dyrehaven", "bellevue"), ("scenic", "quiet", "park"), ("cafe", "restaurant", "public_bathroom"), ("Bellevue Beach", "Dyrehaven"), "https://www.visitcopenhagen.com/copenhagen/planning/cycling-copenhagen", "copenhagen"),
    RouteTemplate("copenhagen-vestamager", "Vestamager Nature Route", "A long greenway concept toward Kalvebod Fælled.", ("amager", "ørestad", "copenhagen"), ("vestamager", "kalvebod fælle", "dragør"), ("quiet", "scenic", "park"), ("cafe", "public_bathroom"), ("Kalvebod Fælled",), "https://www.visitcopenhagen.com/copenhagen/planning/cycling-copenhagen", "copenhagen"),
    RouteTemplate("copenhagen-bella-sky", "Bella Center to Harbour", "A modern south-harbour route concept through Ørestad.", ("ørestad", "amager", "copenhagen"), ("bella center", "kalvebod brygge", "harbour"), ("scenic", "interesting", "quiet"), ("cafe", "restaurant"), ("Bella Center", "Kalvebod Fælled"), "https://international.kk.dk/live/transport-and-parking/cycling", "copenhagen"),
    RouteTemplate("copenhagen-northwest-loop", "Northwest Copenhagen Loop", "A connected neighborhood and lake loop concept.", ("nørrebro", "bispebjerg", "frederiksberg"), ("uttrup", "the lakes", "city centre"), ("quiet", "scenic", "park"), ("cafe", "restaurant"), ("Copenhagen Lakes", "Utterslev Mose"), "https://international.kk.dk/live/transport-and-parking/cycling", "copenhagen"),
    RouteTemplate("barcelona-waterfront", "Barcelona Waterfront", "A seafront route concept connecting Barceloneta, Port Olímpic, and the coast.", ("gothic quarter", "barceloneta", "eixample"), ("port olimpic", "forum", "badalona"), ("scenic", "quiet", "interesting"), ("cafe", "restaurant", "public_bathroom"), ("Barceloneta", "Port Olímpic"), "https://www.barcelona.cat/en/what-to-do-in-bcn/sport/cycling", "barcelona"),
    RouteTemplate("barcelona-collserola", "Barcelona to Collserola", "A hill and park route concept from the city toward Collserola Natural Park.", ("gràcia", "sarria", "eixample"), ("collserola", "tibidabo", "vallvidrera"), ("scenic", "quiet", "park"), ("cafe", "restaurant", "public_bathroom"), ("Tibidabo", "Collserola Natural Park"), "https://www.parcnaturalcollserola.cat/en/", "barcelona"),
    RouteTemplate("barcelona-diagonal-mar", "Diagonal Mar and Forum", "A seafront and park route concept along Barcelona's northeast coast.", ("eixample", "poblenou", "barceloneta"), ("diagonal mar", "forum", "badalona"), ("scenic", "quiet", "interesting"), ("cafe", "restaurant", "public_bathroom"), ("Diagonal Mar", "Parc del Fòrum"), "https://www.barcelona.cat/en/what-to-do-in-bcn/sport/cycling", "barcelona"),
    RouteTemplate("barcelona-montjuic", "Montjuïc Park", "A hilltop park and landmark route concept above the port.", ("poble sec", "parallel", "barcelona"), ("montjuïc", "joan miro", "olympic ring"), ("scenic", "park", "interesting"), ("cafe", "restaurant", "public_bathroom"), ("Montjuïc", "Olympic Ring"), "https://www.barcelona.cat/en/what-to-do-in-bcn/sport/cycling", "barcelona"),
    RouteTemplate("barcelona-tramvia", "Besòs River Greenway", "A river and coast route concept northeast of the city.", ("poblenou", "sant marti", "forum"), ("besòs", "santa coloma", "badalona"), ("quiet", "scenic", "park"), ("cafe", "restaurant"), ("Besòs River",), "https://www.barcelona.cat/en/what-to-do-in-bcn/sport/cycling", "barcelona"),
    RouteTemplate("barcelona-parc-coll", "Parc Güell and Gràcia", "A cultural and hillside route concept through Gràcia.", ("eixample", "gràcia", "sagrada familia"), ("parc güell", "vallcarca", "tibidabo"), ("interesting", "scenic", "park"), ("cafe", "restaurant", "public_bathroom"), ("Parc Güell", "Gràcia"), "https://parkguell.barcelona/en/", "barcelona"),
    RouteTemplate("barcelona-lobregat", "Llobregat Delta", "A flat river and wetlands route concept southwest of Barcelona.", ("sants", "les corts", "hospitalet"), ("llobregat", "el prat", "delta del llobregat"), ("quiet", "scenic", "park"), ("cafe", "restaurant", "public_bathroom"), ("Llobregat Delta",), "https://www.barcelona.cat/en/what-to-do-in-bcn/sport/cycling", "barcelona"),
    RouteTemplate("barcelona-sitges", "Barcelona Coast to Sitges", "A longer coastal route concept toward Sitges.", ("castelldefels", "el prat", "barcelona"), ("sitges", "garraf", "castelldefels"), ("scenic", "quiet", "interesting"), ("cafe", "restaurant", "public_bathroom"), ("Castelldefels", "Garraf coast"), "https://www.barcelona.cat/en/what-to-do-in-bcn/sport/cycling", "barcelona"),
    RouteTemplate("barcelona-horta", "Horta and Guinardó", "A neighborhood and park route concept in northeast Barcelona.", ("gràcia", "eixample", "sagrada familia"), ("horta", "guinardó", "laberint d'horta"), ("quiet", "park", "interesting"), ("cafe", "restaurant"), ("Laberint d'Horta",), "https://www.barcelona.cat/en/what-to-do-in-bcn/sport/cycling", "barcelona"),
    RouteTemplate("barcelona-besos-loop", "Forum to Besòs Loop", "A coastal loop concept linking the Forum and Besòs river.", ("forum", "diagonal mar", "poblenou"), ("besòs", "sant adrià", "forum"), ("scenic", "quiet", "park"), ("cafe", "restaurant", "public_bathroom"), ("Parc del Fòrum", "Besòs River"), "https://www.barcelona.cat/en/what-to-do-in-bcn/sport/cycling", "barcelona"),
    RouteTemplate("barcelona-castelldefels", "Castelldefels Beach", "A low-gradient beach route concept southwest of Barcelona.", ("barceloneta", "el prat", "llobregat"), ("castelldefels", "gavà mar", "airport"), ("scenic", "quiet"), ("cafe", "restaurant", "public_bathroom"), ("Castelldefels Beach",), "https://www.barcelona.cat/en/what-to-do-in-bcn/sport/cycling", "barcelona"),
    RouteTemplate("barcelona-sarria", "Sarrià Green Route", "A quieter hillside and park route concept west of the centre.", ("les corts", "sarria", "gràcia"), ("sarria", "vallvidrera", "collserola"), ("quiet", "scenic", "park"), ("cafe", "restaurant"), ("Sarrià", "Vallvidrera"), "https://www.parcnaturalcollserola.cat/en/", "barcelona"),
    RouteTemplate("barcelona-gothic-montjuic", "Gothic Quarter to Montjuïc", "A landmark-to-park route concept through the old city and port.", ("gothic quarter", "barceloneta", "el born"), ("montjuïc", "poble sec", "olympic ring"), ("interesting", "scenic", "park"), ("cafe", "restaurant", "public_bathroom"), ("Gothic Quarter", "Montjuïc"), "https://www.barcelona.cat/en/what-to-do-in-bcn/sport/cycling", "barcelona"),
    RouteTemplate("barcelona-gracia-bunkers", "Gràcia to Bunkers", "A cultural and viewpoint route concept toward Carmel.", ("gràcia", "eixample", "sagrada familia"), ("bunkers del carmel", "carmel", "guinardó"), ("interesting", "scenic", "park"), ("cafe", "restaurant"), ("Bunkers del Carmel",), "https://www.barcelona.cat/en/what-to-do-in-bcn/sport/cycling", "barcelona"),
    RouteTemplate("barcelona-poblenou-loop", "Poblenou Loop", "A neighborhood, beach, and design route concept.", ("poblenou", "eixample", "barceloneta"), ("poblenou", "diagonal mar", "forum"), ("scenic", "interesting", "quiet"), ("cafe", "restaurant", "public_bathroom"), ("Poblenou", "Mar Bella Beach"), "https://www.barcelona.cat/en/what-to-do-in-bcn/sport/cycling", "barcelona"),
    RouteTemplate("madrid-rio", "Madrid Río", "A riverside greenway concept through Madrid Río and Casa de Campo.", ("centro", "lavapiés", "arganzuela"), ("madrid río", "casa de campo", "moncloa"), ("scenic", "quiet", "park", "interesting"), ("cafe", "restaurant", "public_bathroom"), ("Madrid Río", "Casa de Campo"), "https://www.esmadrid.com/en/madrid-rio-park", "madrid"),
    RouteTemplate("madrid-retiro", "Retiro and Casa de Campo", "A park-to-park route concept connecting Retiro with Madrid's western green spaces.", ("retiro", "salamanca", "atocha"), ("casa de campo", "moncloa", "príncipe pío"), ("scenic", "park", "interesting"), ("cafe", "restaurant", "public_bathroom"), ("El Retiro", "Casa de Campo"), "https://www.esmadrid.com/en/parks-madrid", "madrid"),
    RouteTemplate("madrid-manzanares", "Manzanares River", "A riverside greenway concept through western Madrid.", ("centro", "arganzuela", "atocha"), ("manzanares", "madrid río", "casa de campo"), ("scenic", "quiet", "park"), ("cafe", "restaurant", "public_bathroom"), ("Madrid Río", "Manzanares River"), "https://www.esmadrid.com/en/madrid-rio-park", "madrid"),
    RouteTemplate("madrid-casa-campo-loop", "Casa de Campo Loop", "A large-park loop concept west of central Madrid.", ("moncloa", "príncipe pío", "centro"), ("casa de campo", "lake casa de campo", "zoo"), ("scenic", "quiet", "park"), ("cafe", "restaurant", "public_bathroom"), ("Casa de Campo Lake",), "https://www.esmadrid.com/en/parks-madrid", "madrid"),
    RouteTemplate("madrid-elanio", "El Pardo Greenway", "A woodland route concept toward Monte de El Pardo.", ("moncloa", "fuencarral", "chamartín"), ("el pardo", "monte del pardo", "manzanares"), ("quiet", "scenic", "park"), ("cafe", "restaurant"), ("Monte de El Pardo",), "https://www.esmadrid.com/en/parks-madrid", "madrid"),
    RouteTemplate("madrid-castellana", "Castellana to Santiago Bernabéu", "A central boulevard and landmark route concept.", ("retiro", "salamanca", "chamartín"), ("castellana", "bernabéu", "four towers"), ("interesting", "scenic"), ("cafe", "restaurant"), ("Santiago Bernabéu", "Cuatro Torres"), "https://www.esmadrid.com/en/what-see-do-madrid", "madrid"),
    RouteTemplate("madrid-alcala", "Retiro to Alcalá", "A cultural and park route concept through central Madrid.", ("retiro", "atocha", "lavapiés"), ("puerta de alcalá", "salamanca", "gran vía"), ("interesting", "scenic", "park"), ("cafe", "restaurant", "public_bathroom"), ("Puerta de Alcalá", "El Retiro"), "https://www.esmadrid.com/en/parks-madrid", "madrid"),
    RouteTemplate("madrid-dehesa", "Dehesa de la Villa", "A quiet western park route concept with city views.", ("moncloa", "argüelles", "tetúan"), ("dehesa de la villa", "ciudad universitaria", "puerta de hierro"), ("quiet", "scenic", "park"), ("cafe", "public_bathroom"), ("Dehesa de la Villa",), "https://www.esmadrid.com/en/parks-madrid", "madrid"),
    RouteTemplate("madrid-juan-carlos", "Juan Carlos I Park", "A contemporary park and lake route concept northeast of Madrid.", ("barajas", "canillejas", "chamartín"), ("juan carlos i", "ifema", "parque juan carlos"), ("scenic", "park", "interesting"), ("cafe", "restaurant", "public_bathroom"), ("Juan Carlos I Park",), "https://www.esmadrid.com/en/parks-madrid", "madrid"),
    RouteTemplate("madrid-capricho", "El Capricho and Alameda", "A heritage-garden route concept near Barajas.", ("barajas", "canillejas", "hortaleza"), ("el capricho", "alameda de osuna", "juan carlos i"), ("scenic", "park", "interesting"), ("cafe", "restaurant"), ("El Capricho",), "https://www.esmadrid.com/en/parks-madrid", "madrid"),
    RouteTemplate("madrid-sierra", "Madrid to Sierra Foothills", "A longer green route concept toward the northern foothills.", ("fuencarral", "chamartín", "moncloa"), ("sierra de guadarrama", "tres cantos", "colmenar viejo"), ("scenic", "quiet", "park"), ("cafe", "restaurant", "public_bathroom"), ("Sierra de Guadarrama",), "https://www.esmadrid.com/en/parks-madrid", "madrid"),
    RouteTemplate("madrid-university", "University City Loop", "A campus and park route concept around Moncloa.", ("moncloa", "argüelles", "ciudad universitaria"), ("parque del oeste", "dehesa de la villa", "moncloa"), ("scenic", "quiet", "interesting"), ("cafe", "restaurant"), ("Parque del Oeste", "Ciudad Universitaria"), "https://www.esmadrid.com/en/parks-madrid", "madrid"),
    RouteTemplate("madrid-lago", "Madrid Río to Lago", "A riverside-to-park route concept from Arganzuela to Casa de Campo.", ("arganzuela", "centro", "atocha"), ("lago", "casa de campo", "madrid río"), ("scenic", "park", "quiet"), ("cafe", "restaurant", "public_bathroom"), ("Madrid Río", "Lago de Casa de Campo"), "https://www.esmadrid.com/en/madrid-rio-park", "madrid"),
    RouteTemplate("madrid-dehesa-retiro", "Dehesa to Retiro", "A west-to-central parks route concept across Madrid.", ("dehesa de la villa", "moncloa", "ciudad universitaria"), ("retiro", "atocha", "puerta de alcalá"), ("scenic", "park", "interesting"), ("cafe", "restaurant", "public_bathroom"), ("Dehesa de la Villa", "El Retiro"), "https://www.esmadrid.com/en/parks-madrid", "madrid"),
    RouteTemplate("madrid-north-greenway", "North Madrid Greenway", "A quieter route concept through northern parks and neighborhoods.", ("chamartín", "tetúan", "fuencarral"), ("montecarmelo", "tres olivos", "el pardo"), ("quiet", "scenic", "park"), ("cafe", "restaurant"), ("Monte de El Pardo",), "https://www.esmadrid.com/en/parks-madrid", "madrid"),
    RouteTemplate("paris-seine", "Paris Seine Banks", "A riverside route concept through central Paris.", ("louvre", "notre dame", "bastille"), ("eiffel tower", "invalides", "pont de grenelle"), ("scenic", "interesting", "quiet"), ("cafe", "restaurant", "public_bathroom"), ("Seine River", "Eiffel Tower"), "https://www.paris.fr/pages/velo-et-mobilites-206", "paris"),
    RouteTemplate("paris-canal-saint-martin", "Canal Saint-Martin", "A canal-side route concept through northeast Paris.", ("république", "bastille", "gare du nord"), ("canal saint-martin", "la villette", "parc de la villette"), ("scenic", "quiet", "interesting"), ("cafe", "restaurant"), ("Canal Saint-Martin", "La Villette"), "https://www.paris.fr/pages/velo-et-mobilites-206", "paris"),
    RouteTemplate("paris-bois-boulogne", "Bois de Boulogne", "A large-park route concept west of Paris.", ("16th arrondissement", "porte maillot", "trocadéro"), ("bois de boulogne", "longchamp", "bagatelle"), ("scenic", "quiet", "park"), ("cafe", "restaurant", "public_bathroom"), ("Bois de Boulogne", "Longchamp"), "https://www.paris.fr/pages/les-bois-de-boulogne-et-de-vincennes-177", "paris"),
    RouteTemplate("paris-bois-vincennes", "Bois de Vincennes", "A woodland and lake route concept east of Paris.", ("bastille", "nation", "bercy"), ("bois de vincennes", "vincennes", "lac daumesnil"), ("scenic", "quiet", "park"), ("cafe", "restaurant", "public_bathroom"), ("Bois de Vincennes", "Lac Daumesnil"), "https://www.paris.fr/pages/les-bois-de-boulogne-et-de-vincennes-177", "paris"),
    RouteTemplate("paris-coulée-verte", "Coulée Verte René-Dumont", "A greenway concept through the east side of Paris.", ("bastille", "gare de lyon", "bercy"), ("coulée verte", "vincennes", "nation"), ("scenic", "quiet", "park"), ("cafe", "restaurant"), ("Coulée Verte René-Dumont",), "https://www.paris.fr/pages/la-coulee-verte-rene-dumont-177", "paris"),
    RouteTemplate("paris-parc-andre-citroen", "Parc André-Citroën", "A southwest river and park route concept.", ("eiffel tower", "invalides", "15th arrondissement"), ("parc andré citroën", "pont de garigliano", "boulogne"), ("scenic", "park", "quiet"), ("cafe", "restaurant", "public_bathroom"), ("Parc André-Citroën",), "https://www.paris.fr/pages/les-parcs-et-jardins-203", "paris"),
    RouteTemplate("paris-parc-la-villette", "Parc de la Villette", "A canal and cultural-sites route concept in northeast Paris.", ("gare du nord", "république", "canal saint-martin"), ("la villette", "parc de la villette", "pantin"), ("interesting", "scenic", "park"), ("cafe", "restaurant", "public_bathroom"), ("Parc de la Villette", "Canal de l'Ourcq"), "https://www.paris.fr/pages/le-parc-de-la-villette-180", "paris"),
    RouteTemplate("paris-ourcq", "Canal de l'Ourcq", "A long canal-side route concept toward the northeast suburbs.", ("la villette", "pantin", "paris"), ("canal de l'ourcq", "bobigny", "noisy-le-sec"), ("quiet", "scenic", "interesting"), ("cafe", "restaurant"), ("Canal de l'Ourcq",), "https://www.paris.fr/pages/velo-et-mobilites-206", "paris"),
    RouteTemplate("paris-montparnasse", "Montparnasse to Luxembourg", "A central cultural and park route concept.", ("montparnasse", "saint-germain", "latin quarter"), ("luxembourg gardens", "pantheon", "place denfert-rochereau"), ("interesting", "scenic", "park"), ("cafe", "restaurant", "public_bathroom"), ("Luxembourg Gardens", "Panthéon"), "https://www.paris.fr/pages/les-parcs-et-jardins-203", "paris"),
    RouteTemplate("paris-montmartre", "Montmartre and Canal", "A landmark route concept linking Montmartre to Canal Saint-Martin.", ("montmartre", "pigalle", "gare du nord"), ("canal saint-martin", "la villette", "république"), ("interesting", "scenic", "quiet"), ("cafe", "restaurant"), ("Montmartre", "Canal Saint-Martin"), "https://www.paris.fr/pages/velo-et-mobilites-206", "paris"),
    RouteTemplate("paris-la-defense", "Seine to La Défense", "A westward river and modern-landmark route concept.", ("louvre", "eiffel tower", "16th arrondissement"), ("la défense", "neuilly", "bois de boulogne"), ("scenic", "interesting", "quiet"), ("cafe", "restaurant"), ("La Défense", "Bois de Boulogne"), "https://www.paris.fr/pages/velo-et-mobilites-206", "paris"),
    RouteTemplate("paris-batignolles", "Batignolles Greenway", "A neighborhood park route concept in northwest Paris.", ("opéra", "montmartre", "saint-lazare"), ("batignolles", "parc martin luther king", "clichy"), ("park", "quiet", "interesting"), ("cafe", "restaurant"), ("Parc Martin Luther King",), "https://www.paris.fr/pages/les-parcs-et-jardins-203", "paris"),
    RouteTemplate("paris-bievre", "Bièvre Valley", "A southern park and river route concept toward the Paris edge.", ("latin quarter", "place d'italie", "montparnasse"), ("parc montsouris", "gentilly", "bievre"), ("quiet", "scenic", "park"), ("cafe", "restaurant", "public_bathroom"), ("Parc Montsouris",), "https://www.paris.fr/pages/les-parcs-et-jardins-203", "paris"),
    RouteTemplate("paris-vincennes-loop", "Vincennes Loop", "A park loop concept around Château de Vincennes and Daumesnil.", ("nation", "bastille", "bercy"), ("vincennes", "château de vincennes", "lac daumesnil"), ("scenic", "quiet", "park", "interesting"), ("cafe", "restaurant", "public_bathroom"), ("Château de Vincennes", "Lac Daumesnil"), "https://www.paris.fr/pages/les-bois-de-boulogne-et-de-vincennes-177", "paris"),
    RouteTemplate("paris-ile-saint-denis", "Saint-Denis Canal", "A canal and cultural-sites route concept north of Paris.", ("la villette", "gare du nord", "montmartre"), ("saint-denis", "stade de france", "canal saint-denis"), ("interesting", "scenic", "quiet"), ("cafe", "restaurant"), ("Stade de France", "Canal Saint-Denis"), "https://www.paris.fr/pages/velo-et-mobilites-206", "paris"),
)

_ALLOWED_TAGS = {"scenic", "quiet", "park", "interesting"}
_ALLOWED_STOPS = {"cafe", "restaurant", "public_bathroom", "shop", "bicycle_repair_shop"}


def _normalise(value: str) -> str:
    """Fold accents and punctuation so matching is stable across provider names."""
    folded = unicodedata.normalize("NFKD", value.casefold())
    return re.sub(r"[^a-z0-9]+", " ", folded.encode("ascii", "ignore").decode()).strip()


def validate_route_catalog(catalog: tuple[RouteTemplate, ...] = CITY_ROUTE_TEMPLATES) -> None:
    """Fail fast on malformed curated data instead of silently degrading matches."""
    ids: set[str] = set()
    for template in catalog:
        if not template.template_id or template.template_id in ids:
            raise ValueError(f"Route template ids must be unique: {template.template_id!r}")
        ids.add(template.template_id)
        if not template.city or not template.start_terms or not template.end_terms:
            raise ValueError(f"Route template {template.template_id!r} is missing city or endpoint terms")
        if not template.source_url.startswith("https://"):
            raise ValueError(f"Route template {template.template_id!r} must have an https source")
        if not set(template.tags) <= _ALLOWED_TAGS:
            raise ValueError(f"Route template {template.template_id!r} contains an unsupported tag")
        if not set(template.suggested_stops) <= _ALLOWED_STOPS:
            raise ValueError(f"Route template {template.template_id!r} contains an unsupported stop")


validate_route_catalog()


def match_route_templates(origin: str, destination: str, preferences: list[str] | None = None, requested_stops: list[str] | None = None, city: str = "london") -> list[RouteTemplate]:
    """Return at most two deterministic ideas matching named areas and intent."""
    origin_text, destination_text = _normalise(origin), _normalise(destination)
    def contains(text: str, term: str) -> bool:
        needle = _normalise(term)
        return needle in text if " " in needle else needle in text.split()

    prefs = {_normalise(item) for item in (preferences or [])}
    stops = {_normalise(item) for item in (requested_stops or [])}
    scored: list[tuple[int, RouteTemplate]] = []
    for template in CITY_ROUTE_TEMPLATES:
        if template.city != city:
            continue
        start = any(contains(origin_text, term) for term in template.start_terms)
        end = any(contains(destination_text, term) for term in template.end_terms)
        reverse = any(contains(destination_text, term) for term in template.start_terms) and any(contains(origin_text, term) for term in template.end_terms)
        if not ((start and end) or reverse):
            continue
        score = 4 if start and end else 3
        score += 2 * len(prefs.intersection({_normalise(item) for item in template.tags}))
        score += len(stops.intersection({_normalise(item) for item in template.suggested_stops}))
        scored.append((score, template))
    scored.sort(key=lambda item: (-item[0], item[1].template_id))
    return [template for _, template in scored[:2]]
